[user]
name = "Nils Riedemann"
email = "nils@bleepbloop.studio"

[ui]
default-command = ["status"]
paginate = "never"

# [template-aliases]
# 'format_short_id(id)' = 'id.shortest()'

[aliases]
l = ["log", "-n", "15"]
ll = ["log", "-n", "15", "-r", "::@"]
st = ["status"]
sq = ["squash"]
before = ['new', '--before', '@', '--no-edit']
ci = ['commit', '-i']
cmi = ['commit', '-i', '-m']
cm = ['commit', '-m']
tug = ['bookmark', 'move', '--from', "heads(::@- & bookmarks())", "--to", "@-"]
here = ['bookmark', 'move', '--from', "heads(::@- & bookmarks())", "--to", "@"]
stp = ['log', '--stat', '-r', "@-"]
current = ['log']
